# Generated by Django 5.0.3 on 2024-04-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customersmodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersmodel',
            name='otp',
            field=models.CharField(default='111111', max_length=10),
        ),
    ]
