# Generated by Django 5.0.3 on 2024-04-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customeraddressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersmodel',
            name='is_added_address',
            field=models.BooleanField(default=False),
        ),
    ]
