# Generated by Django 5.0.4 on 2024-04-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_contactusmodel_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='practice_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
