# Generated by Django 5.0.4 on 2024-04-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_practice_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='practice_model',
        ),
    ]
