# Generated by Django 5.0.3 on 2024-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_productsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
