# Generated by Django 5.0.3 on 2024-04-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('on_working', 'On Working')], default='unresolved', max_length=255),
        ),
    ]
