# Generated by Django 5.0.3 on 2024-04-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customersmodel_is_added_address'),
        ('buyer', '0003_cart'),
        ('seller', '0002_remove_productsmodel_id_productsmodel_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartModel',
        ),
    ]
