# Generated by Django 5.0.3 on 2024-04-19 05:46

import master.utils.LO_UNIQUE.unique_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(upload_to=master.utils.LO_UNIQUE.unique_filename.genrate_unique_filename),
        ),
    ]
