# Generated by Django 5.0.3 on 2024-04-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customersmodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersmodel',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
