file = open('sample.txt', 'r')
# print(file.read())
# print(file.read(9))
# print(file.readlines())
# print(file.readline())
# print(file.readline())
# print(file.readline())
# print(file.readline())
# print(file.readline())
# print(file.readline())
# print(file.readline())
# print(file.readline())
# print(file.readline())
# print(file.readline())
file.close()
print(file.read())