# Generated by Django 5.0.4 on 2024-04-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0003_department_delete_club_student_age_alter_book_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='manage_institute.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='manage_institute.department'),
        ),
    ]
