# Generated by Django 5.0.4 on 2024-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0006_alter_student_department_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
