# Generated by Django 5.0.4 on 2024-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0007_student_email_student_password_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
