# Generated by Django 5.0.4 on 2024-04-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_institute', '0008_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
